"""How an agent presents itself in the portal catalog and Agent Studio.

These fields exist because the portal had nowhere to read them from. An agent
lived in the control plane with a prompt and a template binding, and the
catalog still had to invent an icon, a category and a price — or omit the agent
entirely, which is what it did.

They are first-class fields rather than keys inside ``config`` for one reason:
``config`` is opaque to this service and is passed through to the engine, so
anything in it is a private arrangement between an agent and its workflow. What
the catalog renders is a public contract, and a schema is how a contract gets
enforced instead of remembered.

``stages`` is the one to read carefully. For the eleven hand-written
agent-engine workflows the stages are TypeScript, not data: they are recorded
here so the Studio can SHOW what an agent does, and they are documented as
read-only because editing this list would change a page and not a program.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from app.core.enums import Capability


class AgentReadiness(BaseModel):
    """Workspace records a client needs before this agent can run.

    Paths under ``clients/<slug>/``, in the vocabulary
    ``report_client_readiness.py`` already uses -- ``client/profile``,
    ``client/config:xHandle``, ``strategy/x-agent``, ``topics/catalog``.

    ``hard`` stops the run; ``soft`` degrades it. Keeping them apart is not
    tidiness: the readiness report's own note says calling a soft gap "blocked"
    makes the report useless by crying wolf on agents that would in fact
    produce something. A planner needs the same distinction to answer "can this
    client have a post today" honestly.
    """

    hard: list[str] = Field(default_factory=list)
    soft: list[str] = Field(default_factory=list)


class AgentStage(BaseModel):
    """One step of an agent's workflow, for display.

    Mirrors the workflow's real step id so the Studio and a run's step trace
    line up — a reader comparing the two is the whole point of showing them.
    """

    id: str = Field(min_length=1, max_length=128)
    label: str = Field(min_length=1, max_length=255)
    description: str | None = None
    #: A gate pauses for a human. Worth showing, because it is the difference
    #: between an agent that finishes on its own and one that waits.
    #:
    #: Generated rather than hand-set. It was false on all 250 recorded stages
    #: until `generate_engine_stages.py` learned the two ways the engine
    #: actually declares a gate: through the shared review-cycle primitive
    #: (invisible to a scan of the agent's own source), and inside a ternary
    #: whose other arm is an autoApprove `code` step with the same id (which
    #: was being recorded instead of the gate).
    is_gate: bool = False
    #: Which human gate: `batch_review`, `prompt_set_review`,
    #: `fix_generation_review`. The engine's own vocabulary, not ours.
    gate_kind: str | None = Field(default=None, max_length=64)
    #: Which kind of step this is, in AGENT-ENGINE's own vocabulary --
    #: ``"agent"`` for a model step, matching its ``StepKindSchema`` and the
    #: ``kind`` field in ``engine_stages.json``.
    #:
    #: This field first shipped as ``Literal["ai", "code", "gate"]``, which no
    #: seeded stage could ever satisfy: every model step in the engine is
    #: ``"agent"``, so all 206 stages fell back to ``"code"`` and the Studio's
    #: per-stage model picker -- rendered only on model steps -- appeared on
    #: none of them. Naming a concept differently on each side of a wire is how
    #: a feature ships looking complete and does nothing.
    kind: Literal["agent", "code", "gate"] = "code"
    #: Which prompt this stage loads, as ``"<promptId>@<version>"`` -- the
    #: agent class's own ``skillRef``. Absent on code steps, and on the shared
    #: terminal guardrail, which builds its prompt inline from the client's
    #: forbidden-topic list and so has nothing to edit.
    #:
    #: This is what lets the Studio put the right prompt editor beside the
    #: right stage. It is a mirror of a fact the engine owns, generated by
    #: ``scripts/generate_engine_stages.py`` from the workflow sources, never
    #: authored here.
    skill_ref: str | None = Field(default=None, max_length=200)
    #: A document id from the ``models`` collection, overriding whatever model
    #: this stage is compiled to use. Null means "leave the stage alone".
    #:
    #: Settable even though ``stages_read_only`` is true for the hand-written
    #: workflows, and the distinction is the point: the stage LIST is code and
    #: editing it here would change a page and not a program, but which model a
    #: stage runs on is configuration the engine reads per run. The engine
    #: applies it through ``AgentContext.stageModels``, resolved at the one
    #: place every agent step passes through.
    model_id: str | None = Field(default=None, max_length=128)


class AgentInputDef(BaseModel):
    """One field the run dialog asks for before dispatching.

    Deliberately the same vocabulary as karosCMO's ``DynamicAgentInputDef``
    (key/type/label/helpText/required/placeholder/options), so the portal can
    render these with the control it already has rather than a second one that
    drifts.
    """

    key: str = Field(min_length=1, max_length=64, pattern=r"^[a-zA-Z][a-zA-Z0-9_]*$")
    type: str = Field(default="text", max_length=32)
    label: str = Field(min_length=1, max_length=255)
    help_text: str | None = None
    required: bool = False
    placeholder: str | None = None
    options: list[str] = Field(default_factory=list)


class AgentPresentation(BaseModel):
    """The catalog/Studio half of an agent record."""

    #: lucide icon name, matching karosCMO's own icon component.
    icon: str | None = Field(default=None, max_length=64)
    category: str | None = Field(default=None, max_length=64)
    #: Credits charged per run. Null means "use the platform default" rather
    #: than "free" — a zero here would be a priced decision, and absent is not.
    credit_cost: int | None = Field(default=None, ge=0)
    #: Whether the agent appears in client-facing surfaces at all.
    is_public: bool = True
    required_inputs: list[AgentInputDef] = Field(default_factory=list)
    #: Read-only for hand-written workflows: their stages are code.
    stages: list[AgentStage] = Field(default_factory=list)
    #: True when `stages` describes compiled code rather than editable data.
    stages_read_only: bool = True

    def as_document(self) -> dict[str, Any]:
        return self.model_dump(mode="json")


class AgentDescriptorFields(BaseModel):
    """The half of the C4 descriptor that cannot be derived from a workflow.

    Everything here is a product statement about what an agent is FOR, so it is
    written once in this catalog -- which is already the source of truth for
    agent identity -- and consumed by the portal, never hand-written there.
    ``docs/contracts/C4-capability-descriptor.md`` §7.2 is the ownership rule.

    Not a separate collection or endpoint: these are fields on the agent
    document, which is what C4 §4 means by "or a field on AgentRead". A second
    surface serving the same rows would be a copy to keep in step.
    """

    capabilities: list[Capability] = Field(default_factory=list)
    #: Channels this agent publishes to, lowercase: "x", "linkedin",
    #: "instagram", "tiktok", "reddit", "web", "email". Empty for an agent that
    #: produces no channel-bound artefact, e.g. a research report.
    platforms: list[str] = Field(default_factory=list)
    #: Whether `mediaAssets` on the run input means anything to this agent.
    #: The router asks before accepting an upload, rather than passing files to
    #: a workflow that ignores them and reporting success.
    consumes_media: bool = False
    #: Whether the agent honours C3's `targetDate`. False does not mean the
    #: work cannot be scheduled -- the deliverable can still be held and
    #: published later -- it means the AGENT does not read the date, so the
    #: promise belongs to delivery rather than to the run.
    supports_target_date: bool = False
    #: The portal keys that route here. A LIST, because the map it replaces is
    #: not one-to-one: a channel's setup key and its writer key both land on
    #: the one drafting agent now that setup is inlined as `00-channel-setup`.
    custom_agent_keys: list[str] = Field(default_factory=list)
    #: Human gates on the path, by kind, in step order. A planner promising a
    #: client "you will get a post now" has to know a `batch_review` sits in
    #: the middle with a 24-hour timeout. Derived from `stages`.
    gates: list[str] = Field(default_factory=list)
    readiness: AgentReadiness = Field(default_factory=AgentReadiness)
