#!/usr/bin/env python3
"""Generate ``engine_stages.json`` from agent-engine's own workflow sources.

``seed_all_agents.py``'s docstring has always said this file is generated by
"walking every ``wf.step.code``/``.agent``/``.gate`` call". It described a
script that was never committed, so in practice the stage list was produced by
hand once and drifted -- which is the exact failure that docstring warns about.
This is that script.

It reads three things out of each workflow and nothing else, so the output is
derived rather than authored:

* the IDS of the ``wf.step.*`` calls -- the stage list,
* which of the three primitives each used -- the stage ``kind``,
* for an ``.agent`` call, the ``skillRef`` of the agent class it runs -- which
  is what lets the Studio put the right prompt next to the right stage.

## Why skillRef has to be resolved rather than read

A workflow step id and its agent's own id are different names for different
things: ``wf.step.agent("10-draft-post", draftAgent, ...)`` runs
``XDraftAgent``, whose config says ``skillRef: "x-draft@1"``. The step id is
where it sits in the run; the skillRef is which prompt it loads. So resolution
is three hops -- step id, to the variable, to the class, to its skillRef --
and they live in different files.

## Deliberately not a TypeScript parser

Regex over source is usually the wrong tool and is the right one here for one
reason: the alternative is this Python service shelling out to the TypeScript
compiler over another repository. The patterns are narrow, each matches a
convention this codebase follows without exception, and ``--check`` fails
loudly when a workflow stops matching rather than silently emitting a short
list.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

#: agent-engine sits beside this repository in every environment this runs in.
DEFAULT_ENGINE_ROOT = Path(__file__).resolve().parents[2] / "agent-engine"
OUT_FILE = Path(__file__).with_name("engine_stages.json")

#: The step id is always the first argument and always a literal — a computed
#: one would break the durable store's own checkpoint keys.
STEP_CALL = re.compile(r"wf\.step\.(code|agent|gate)\(\s*[\"'`]([^\"'`$]+)[\"'`]")

#: A templated id, e.g. `05-write-copy-attempt-${attempt}`: one stage a
#: workflow may run several times, not several stages.
TEMPLATED_CALL = re.compile(r"wf\.step\.(code|agent|gate)\(\s*`([^`$]*)\$\{")

#: `const draftAgent = new XDraftAgent({...})`
AGENT_BINDING = re.compile(r"const\s+(\w+)\s*=\s*new\s+(\w+)\s*\(")

#: The agent an `.agent` call runs — either a variable or constructed inline.
AGENT_ARG = re.compile(r"wf\.step\.agent\(\s*[^,]+,\s*(?:new\s+(\w+)|(\w+))")

SKILL_REF = re.compile(r"skillRef:\s*\"([^\"]+)\"")

#: Step ids the SHARED terminal guardrail contributes (packages/workflow's
#: `runTopicGuardrail`). Identifiers, not prompt text: the guardrail builds its
#: system prompt inline from the client's own forbidden-topic list, so it has
#: no skillRef and nothing for the Studio to edit. Listed here because they
#: come from shared code rather than from any one workflow's source.
GUARDRAIL_STEPS = [("guardrail-verify-load-topics", "code"), ("guardrail-verify", "agent")]


#: `case "x-agent": return createXAgentWorkflow(deps)` — the engine's own
#: product-to-workflow mapping, and the only place that association exists.
#: Keying off directory names instead was wrong twice over: one package can
#: hold two products (setup-agents) and one can hold a second, unrelated
#: workflow (branded-shorts' style-exploration onboarding).
PRODUCT_CASE = re.compile(
    r"case\s+\"([a-z0-9-]+)\":\s*\{?\s*(?:.*?)return\s+(create\w+)\(", re.DOTALL
)

WIRING_FILE = ("apps", "agent-server", "src", "wiring", "workflows.ts")


def collapse_retry_suffix(step_id: str) -> str:
    """`05-write-copy-attempt-1` and `05-write-copy-attempt-` -> `05-write-copy`.

    A templated id contributes only its literal prefix, so the trailing
    `-attempt-` arrives without a number. Both forms are one stage a workflow
    may run several times, never several stages.
    """
    trimmed = re.sub(r"-attempt-?\d*$", "", step_id)
    return trimmed.rstrip("-")


def order_key(step_id: str) -> tuple[float, str]:
    """Recovers a step's intended position from its own `NN-` prefix.

    Mirrors agent-engine's own `stepOrderKey` in `apps/agent-server/src/report.ts`
    — the same convention every step id in that repo follows.
    """
    match = re.match(r"^(\d+)", step_id)
    return (float(match.group(1)) if match else float("inf"), step_id)


def class_skill_refs(engine_root: Path) -> dict[str, str]:
    """Every agent class in the engine mapped to the skillRef it declares."""
    refs: dict[str, str] = {}
    for path in (engine_root / "agents").rglob("*.ts"):
        if "__tests__" in path.parts or "dist" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in re.finditer(r"class\s+(\w+)\s+extends\s+BaseAgent", text):
            tail = text[match.end() :]
            ref = SKILL_REF.search(tail[:2000])
            if ref:
                refs[match.group(1)] = ref.group(1)
    return refs


def product_factories(engine_root: Path) -> dict[str, str]:
    """Product id -> the workflow factory the engine dispatches it to."""
    text = (engine_root.joinpath(*WIRING_FILE)).read_text(encoding="utf-8")
    body = text[text.index("switch (productId)") :] if "switch (productId)" in text else text
    return {product: factory for product, factory in PRODUCT_CASE.findall(body)}


def factory_source(engine_root: Path, factory: str) -> Path | None:
    """The file that exports one workflow factory."""
    needle = f"export function {factory}("
    for path in (engine_root / "agents").rglob("*.ts"):
        if "__tests__" in path.parts or "dist" in path.parts:
            continue
        if needle in path.read_text(encoding="utf-8", errors="replace"):
            return path
    return None


def stages_for_workflow(path: Path, refs: dict[str, str]) -> list[dict[str, Any]]:
    """Every stage ONE workflow runs, in run order, with skillRefs where they exist.

    Scoped to the single file that exports the factory, not the whole package
    directory: branded-shorts keeps its Style Exploration onboarding beside its
    main pipeline, and scanning the directory merged the two into one 24-stage
    fiction.
    """
    found: dict[str, dict[str, Any]] = {}
    skipped_dynamic: set[str] = set()

    text = path.read_text(encoding="utf-8", errors="replace")

    # Bindings WITH positions, because a flat name->class map is wrong when
    # a name is reused: tiktok-agent constructs both its agents into a
    # variable called `agent`, so a flat map made 03a-moment resolve to
    # tiktok-commentary. The binding that applies is the nearest one
    # ABOVE the call.
    bindings = [(m.start(), m.group(1), m.group(2)) for m in AGENT_BINDING.finditer(text)]

    def agent_class_at(pos: int, var: str, inline: str) -> str:
        if inline:
            return inline
        candidates = [cls for at, name, cls in bindings if name == var and at < pos]
        return candidates[-1] if candidates else ""

    agent_calls = {
        m.start(): agent_class_at(m.start(), m.group(2) or "", m.group(1) or "")
        for m in AGENT_ARG.finditer(text)
    }

    calls = [(m.start(), m.group(1), m.group(2)) for m in STEP_CALL.finditer(text)]
    calls += [(m.start(), m.group(1), m.group(2)) for m in TEMPLATED_CALL.finditer(text)]
    for _pos, kind, raw_id in sorted(calls):
        step_id = collapse_retry_suffix(raw_id)
        if not step_id:
            continue
        # A genuinely computed id, e.g. `06${"bd"[tierIndex-1]}-${tier.id}-...`,
        # leaves only its numeric prefix behind. Emitting "06" as a stage
        # would put a label in the Studio that matches no step in any run
        # trace, which is worse than the stage being absent — the whole
        # point of showing stages is that a reader can line them up against
        # a run. Skipped loudly instead.
        if re.fullmatch(r"\d+[a-z]?", step_id):
            skipped_dynamic.add(raw_id)
            continue
        entry: dict[str, Any] = {"id": step_id, "kind": kind}
        if kind == "agent":
            cls = agent_calls.get(_pos, "")
            if refs.get(cls):
                entry["skill_ref"] = refs[cls]
        # First writer wins, but a later one carrying a skillRef upgrades it.
        if step_id in found and "skill_ref" not in found[step_id] and "skill_ref" in entry:
            found[step_id] = entry
        elif step_id not in found:
            found[step_id] = entry

    if "runTopicGuardrail(" in text:
        for gid, gkind in GUARDRAIL_STEPS:
            found.setdefault(gid, {"id": gid, "kind": gkind})

    for raw in sorted(skipped_dynamic):
        print(
            f"  ! {path.name}: step id `{raw}` is computed at run time — omitted", file=sys.stderr
        )

    return [found[k] for k in sorted(found, key=order_key)]


def generate(engine_root: Path) -> dict[str, list[dict[str, Any]]]:
    refs = class_skill_refs(engine_root)
    factories = product_factories(engine_root)
    if not factories:
        sys.exit("could not read any product->factory cases from the engine's wiring/workflows.ts")

    out: dict[str, list[dict[str, Any]]] = {}
    for product, factory in sorted(factories.items()):
        source = factory_source(engine_root, factory)
        if source is None:
            print(f"  ! {product}: no file exports {factory}() — skipped", file=sys.stderr)
            continue
        stages = stages_for_workflow(source, refs)
        if stages:
            out[product] = stages
        else:
            print(
                f"  ! {product}: {source.name} exported {factory}() but declared no steps",
                file=sys.stderr,
            )
    return out


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--engine-root", type=Path, default=DEFAULT_ENGINE_ROOT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed file differs, without writing. For CI.",
    )
    args = parser.parse_args()

    if not (args.engine_root / "agents").is_dir():
        sys.exit(f"no agents/ directory under {args.engine_root} — pass --engine-root")

    generated = generate(args.engine_root)
    rendered = json.dumps(generated, indent=2, ensure_ascii=False) + "\n"

    total = sum(len(v) for v in generated.values())
    with_refs = sum(1 for v in generated.values() for s in v if s.get("skill_ref"))
    model_steps = sum(1 for v in generated.values() for s in v if s["kind"] == "agent")
    print(
        f"{len(generated)} agents, {total} stages, "
        f"{model_steps} model steps, {with_refs} with a skillRef"
    )

    if args.check:
        current = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.is_file() else ""
        if current != rendered:
            sys.exit(
                f"{OUT_FILE.name} is stale — regenerate it with "
                "`python scripts/generate_engine_stages.py` and commit the result."
            )
        print("up to date")
        return 0

    OUT_FILE.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
